version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb
    env_file: .env
    volumes: 
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
  nginx:
    container_name: nginx
    networks:
      - inception
    volumes: 
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
    build: ./requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
  wordpress:
    container_name: wordpress
    env_file: .env
    networks:
      - inception
    volumes: 
      - wordpress_data:/var/www/html
    build: ./requirements/wordpress
    restart: on-failure
    depends_on:
      - mariadb

volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vcornill/data/wordpress'
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vcornill/data/mariadb'

networks:
  inception:
     driver: bridge
