# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MakeFile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vcornill <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/08/22 14:59:25 by vcornill          #+#    #+#              #
#    Updated: 2023/08/22 17:30:49 by vcornill         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CFLAGS = gcc -Wall -Werror -Wextra
EXEC = prog
SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)

all : $(EXEC)

%.o : %.c
	$(CFLAGS) -o $@ -c $<
clean :
	rm -rf *.o
mrproper : clean
	rm -rf $(EXEC)

$(EXEC) : $(OBJ)
	$(CFLAGS) -o $@ $^

#$@ #NOMCIBLE
#$< #NOMPREMIEREDEPENDANCE
#$^ #LISTEDEPENDANCES
#$? #LISTDEPENDANCESplus recentes
#$* #nom du fichier sans extentions
